import { Inter } from 'next/font/google';
import localFont from 'next/font/local';
import StyledJsxRegistry from './registry';

const inter = Inter({ subsets: ['latin'] });

const myFont = localFont({
  src: [
    { path: '../../public/fonts/UhBee Kang-Ja-Regular.ttf' },
    { path: '../../public/fonts/UhBee Kang-Ja-Bold.ttf' },
  ],
  display: 'swap',
  variable: '--uhbee',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${myFont.className}`}>
        <StyledJsxRegistry>{children}</StyledJsxRegistry>
      </body>
    </html>
  );
}
